/**
 * Customers + Customer Transactions API client (Phase 3 Frontend).
 *
 * Wraps the typed apiGet/apiPost/apiPatch/apiDelete helpers from `lib/api.ts`.
 * Idempotency-Key for state-changing requests is auto-generated by the
 * shared axios interceptor (lib/http.ts). Callers may override by passing
 * a `headers['Idempotency-Key']` config.
 */

import type {
  CancelTransactionInput,
  CreateAdjustmentInput,
  CreateCustomerInput,
  CreateDebtInput,
  CreatePaymentInput,
  GrantGraceInput,
  ListCustomersQuery,
  ListTransactionsQuery,
  SetCreditLimitInput,
  UpdateCustomerInput,
} from '@grocery/shared';

import { apiDelete, apiGet, apiPatch, apiPost } from '../api';

// ─── Types (mirror Prisma + service responses) ─────────────────────
export type CustomerStatus = 'ACTIVE' | 'FROZEN' | 'GRACE_PERIOD';

export interface Customer {
  id: string;
  storeId?: string;
  name: string;
  phone: string | null;
  whatsappPhone: string | null;
  address?: string | null;
  notes?: string | null;
  openingBalance?: string | number;
  currentBalance: string | number;
  creditLimit: string | number | null;
  status: CustomerStatus;
  graceUntil: string | null;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string | null;
  createdBy?: { id: string; username: string; fullName: string };
  reminderSettings?: {
    id: string;
    enabled: boolean;
    frequency: string;
    lastSentAt: string | null;
    templateId: string | null;
  } | null;
}

export interface CustomerBalance {
  id: string;
  name: string;
  currentBalance: string | number;
  openingBalance?: string | number;
  creditLimit: string | number | null;
  status: CustomerStatus;
}

export type CustomerTransactionType = 'DEBT' | 'PAYMENT' | 'ADJUSTMENT' | 'OPENING';

export interface CustomerTransaction {
  id: string;
  customerId: string;
  type: CustomerTransactionType;
  amount: string | number;
  balanceBefore: string | number;
  balanceAfter: string | number;
  notes: string | null;
  cancelledAt: string | null;
  cancelledById: string | null;
  cancelReason: string | null;
  referenceType: string | null;
  referenceId: string | null;
  createdById: string;
  createdAt: string;
  createdBy?: { id: string; username: string; fullName: string };
  cancelledBy?: { id: string; username: string; fullName: string } | null;
}

export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface Paged<T> {
  items: T[];
  meta: PaginationMeta;
}

export interface Statement {
  customer: CustomerBalance;
  items: CustomerTransaction[];
  meta: PaginationMeta;
}

// ─── Customers API ─────────────────────────────────────────────────
export const customersApi = {
  list: (params: Partial<ListCustomersQuery> = {}) =>
    apiGet<Paged<Customer>>('/customers', { params }),

  get: (id: string) => apiGet<Customer>(`/customers/${id}`),

  getBalance: (id: string) => apiGet<CustomerBalance>(`/customers/${id}/balance`),

  getStatement: (id: string, params: { page?: number; limit?: number } = {}) =>
    apiGet<Statement>(`/customers/${id}/statement`, { params }),

  create: (data: CreateCustomerInput) => apiPost<Customer, CreateCustomerInput>('/customers', data),

  update: (id: string, data: UpdateCustomerInput) =>
    apiPatch<Customer, UpdateCustomerInput>(`/customers/${id}`, data),

  delete: (id: string) => apiDelete<{ ok: true }>(`/customers/${id}`),

  freeze: (id: string) => apiPost<Customer, never>(`/customers/${id}/freeze`),

  unfreeze: (id: string) => apiPost<Customer, never>(`/customers/${id}/unfreeze`),

  grantGrace: (id: string, data: GrantGraceInput) =>
    apiPost<Customer, { graceUntil: string }>(`/customers/${id}/grant-grace`, {
      graceUntil:
        data.graceUntil instanceof Date
          ? data.graceUntil.toISOString()
          : new Date(data.graceUntil as unknown as string).toISOString(),
    }),

  setCreditLimit: (id: string, data: SetCreditLimitInput) =>
    apiPost<Customer, SetCreditLimitInput>(`/customers/${id}/credit-limit`, data),
};

// ─── Customer Transactions API ─────────────────────────────────────
export const customerTransactionsApi = {
  list: (customerId: string, params: Partial<ListTransactionsQuery> = {}) =>
    apiGet<Paged<CustomerTransaction>>(`/customers/${customerId}/transactions`, { params }),

  createDebt: (customerId: string, data: CreateDebtInput) =>
    apiPost<CustomerTransaction, CreateDebtInput>(
      `/customers/${customerId}/transactions/debt`,
      data,
    ),

  createPayment: (customerId: string, data: CreatePaymentInput) =>
    apiPost<CustomerTransaction, CreatePaymentInput>(
      `/customers/${customerId}/transactions/payment`,
      data,
    ),

  createAdjustment: (customerId: string, data: CreateAdjustmentInput) =>
    apiPost<CustomerTransaction, CreateAdjustmentInput>(
      `/customers/${customerId}/transactions/adjustment`,
      data,
    ),

  cancel: (customerId: string, txId: string, data: CancelTransactionInput) =>
    apiPost<CustomerTransaction & { newBalance: number }, CancelTransactionInput>(
      `/customers/${customerId}/transactions/${txId}/cancel`,
      data,
    ),
};
