/**
 * Suppliers + Supplier Transactions API client (Phase 4 Frontend).
 *
 * Mirrors the customers API client. Idempotency-Key for state-changing
 * requests is auto-generated by the shared axios interceptor.
 */

import type {
  CancelSupplierTransactionInput,
  CreateSupplierAdjustmentInput,
  CreateSupplierInput,
  CreateSupplierPaymentInput,
  ListSupplierTransactionsQuery,
  ListSuppliersQuery,
  UpdateSupplierInput,
} from '@grocery/shared';

import { apiDelete, apiGet, apiPatch, apiPost } from '../api';

// ─── Types ─────────────────────────────────────────────────────────
export interface Supplier {
  id: string;
  storeId?: string;
  name: string;
  phone: string | null;
  whatsappPhone: string | null;
  address?: string | null;
  notes?: string | null;
  openingBalance?: string | number;
  currentBalance: string | number;
  isActive: boolean;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string | null;
  createdBy?: { id: string; username: string; fullName: string };
}

export interface SupplierBalance {
  id: string;
  name: string;
  currentBalance: string | number;
  openingBalance?: string | number;
  isActive: boolean;
}

export type SupplierTransactionType = 'OPENING' | 'CREDIT_PURCHASE' | 'PAYMENT' | 'ADJUSTMENT';

export interface SupplierTransaction {
  id: string;
  supplierId: string;
  type: SupplierTransactionType;
  amount: string | number;
  balanceBefore: string | number;
  balanceAfter: string | number;
  notes: string | null;
  cancelledAt: string | null;
  cancelledById: string | null;
  cancelReason: string | null;
  referenceType: string | null;
  referenceId: string | null;
  createdById: string;
  createdAt: string;
  createdBy?: { id: string; username: string; fullName: string };
  cancelledBy?: { id: string; username: string; fullName: string } | null;
}

export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface Paged<T> {
  items: T[];
  meta: PaginationMeta;
}

export interface SupplierStatement {
  supplier: SupplierBalance;
  items: SupplierTransaction[];
  meta: PaginationMeta;
}

// ─── Suppliers API ─────────────────────────────────────────────────
export const suppliersApi = {
  list: (params: Partial<ListSuppliersQuery> = {}) =>
    apiGet<Paged<Supplier>>('/suppliers', { params }),

  get: (id: string) => apiGet<Supplier>(`/suppliers/${id}`),

  getBalance: (id: string) => apiGet<SupplierBalance>(`/suppliers/${id}/balance`),

  getStatement: (id: string, params: { page?: number; limit?: number } = {}) =>
    apiGet<SupplierStatement>(`/suppliers/${id}/statement`, { params }),

  create: (data: CreateSupplierInput) => apiPost<Supplier, CreateSupplierInput>('/suppliers', data),

  update: (id: string, data: UpdateSupplierInput) =>
    apiPatch<Supplier, UpdateSupplierInput>(`/suppliers/${id}`, data),

  delete: (id: string) => apiDelete<{ ok: true }>(`/suppliers/${id}`),

  restore: (id: string) => apiPost<Supplier, never>(`/suppliers/${id}/restore`),
};

// ─── Supplier Transactions API ─────────────────────────────────────
export const supplierTransactionsApi = {
  list: (supplierId: string, params: Partial<ListSupplierTransactionsQuery> = {}) =>
    apiGet<Paged<SupplierTransaction>>(`/suppliers/${supplierId}/transactions`, { params }),

  createPayment: (supplierId: string, data: CreateSupplierPaymentInput) =>
    apiPost<SupplierTransaction, CreateSupplierPaymentInput>(
      `/suppliers/${supplierId}/transactions/payment`,
      data,
    ),

  createAdjustment: (supplierId: string, data: CreateSupplierAdjustmentInput) =>
    apiPost<SupplierTransaction, CreateSupplierAdjustmentInput>(
      `/suppliers/${supplierId}/transactions/adjustment`,
      data,
    ),

  cancel: (supplierId: string, txId: string, data: CancelSupplierTransactionInput) =>
    apiPost<SupplierTransaction & { newBalance: number }, CancelSupplierTransactionInput>(
      `/suppliers/${supplierId}/transactions/${txId}/cancel`,
      data,
    ),
};
